// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package router

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccessService creates a new instance of MockAccessService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessService {
	mock := &MockAccessService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccessService is an autogenerated mock type for the AccessService type
type MockAccessService struct {
	mock.Mock
}

type MockAccessService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessService) EXPECT() *MockAccessService_Expecter {
	return &MockAccessService_Expecter{mock: &_m.Mock}
}

// CheckAccess provides a mock function for the type MockAccessService
func (_mock *MockAccessService) CheckAccess(userId uint, fqdn string, path string, method string) (bool, error) {
	ret := _mock.Called(userId, fqdn, path, method)

	if len(ret) == 0 {
		panic("no return value specified for CheckAccess")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, string, string, string) (bool, error)); ok {
		return returnFunc(userId, fqdn, path, method)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, string, string, string) bool); ok {
		r0 = returnFunc(userId, fqdn, path, method)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(uint, string, string, string) error); ok {
		r1 = returnFunc(userId, fqdn, path, method)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccessService_CheckAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAccess'
type MockAccessService_CheckAccess_Call struct {
	*mock.Call
}

// CheckAccess is a helper method to define mock.On call
//   - userId uint
//   - fqdn string
//   - path string
//   - method string
func (_e *MockAccessService_Expecter) CheckAccess(userId interface{}, fqdn interface{}, path interface{}, method interface{}) *MockAccessService_CheckAccess_Call {
	return &MockAccessService_CheckAccess_Call{Call: _e.mock.On("CheckAccess", userId, fqdn, path, method)}
}

func (_c *MockAccessService_CheckAccess_Call) Run(run func(userId uint, fqdn string, path string, method string)) *MockAccessService_CheckAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccessService_CheckAccess_Call) Return(b bool, err error) *MockAccessService_CheckAccess_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAccessService_CheckAccess_Call) RunAndReturn(run func(userId uint, fqdn string, path string, method string) (bool, error)) *MockAccessService_CheckAccess_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterRoute provides a mock function for the type MockAccessService
func (_mock *MockAccessService) RegisterRoute(subdomain string, path string, method string, role string) error {
	ret := _mock.Called(subdomain, path, method, role)

	if len(ret) == 0 {
		panic("no return value specified for RegisterRoute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = returnFunc(subdomain, path, method, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccessService_RegisterRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRoute'
type MockAccessService_RegisterRoute_Call struct {
	*mock.Call
}

// RegisterRoute is a helper method to define mock.On call
//   - subdomain string
//   - path string
//   - method string
//   - role string
func (_e *MockAccessService_Expecter) RegisterRoute(subdomain interface{}, path interface{}, method interface{}, role interface{}) *MockAccessService_RegisterRoute_Call {
	return &MockAccessService_RegisterRoute_Call{Call: _e.mock.On("RegisterRoute", subdomain, path, method, role)}
}

func (_c *MockAccessService_RegisterRoute_Call) Run(run func(subdomain string, path string, method string, role string)) *MockAccessService_RegisterRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccessService_RegisterRoute_Call) Return(err error) *MockAccessService_RegisterRoute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccessService_RegisterRoute_Call) RunAndReturn(run func(subdomain string, path string, method string, role string) error) *MockAccessService_RegisterRoute_Call {
	_c.Call.Return(run)
	return _c
}
